name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        # with:
        #   # test: test
      - run: npx cypress run --group AdminSpecs --spec 'cypress/e2e/adminSpecs/login.cy.js' --record --key 14eb653f-0cda-47fc-9684-9e86bd3f2f66 &
          npx cypress run --group AdminSpecs --spec 'cypress/e2e/adminSpecs/actions.cy.js' --record --key 14eb653f-0cda-47fc-9684-9e86bd3f2f66 
      - run: npx cypress run --group UserSpecs --spec 'cypress/e2e/userSpecs/mainPage.cy.js' --record --key 14eb653f-0cda-47fc-9684-9e86bd3f2f66 &
          npx cypress run --group UserSpecs --spec 'cypress/e2e/userSpecs/booling.cy.js' --record --key 14eb653f-0cda-47fc-9684-9e86bd3f2f66 