name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        # with:
        #   # test: test
      - run: npx cypress run --spec 'cypress/e2e/adminSpecs/*.js' --group AdminSpecs --ci-build-id 4  --parallel --record --key 14eb653f-0cda-47fc-9684-9e86bd3f2f66  --browser chrome
      - run: npx cypress run --spec 'cypress/e2e/userSpecs/*.js' --group UserSpecs --ci-build-id 4 --parallel --record --key 14eb653f-0cda-47fc-9684-9e86bd3f2f66 --browser edge