name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          # test: test
      - run: npx cypress run --spec 'cypress/e2e/login.cy.js' --record --key 14eb653f-0cda-47fc-9684-9e86bd3f2f66 &
          npx cypress run --spec 'cypress/e2e/mainPage.cy.js' --record --key 14eb653f-0cda-47fc-9684-9e86bd3f2f66 &
          npx cypress run --spec 'cypress/e2e/booking.cy.js' --record --key 14eb653f-0cda-47fc-9684-9e86bd3f2f66 
